---
title: "Simulation 20 predictors"
author: "Hidde van de Beek"
date: "2024-01-31"
output: html_document
---
```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Setup
### Libraries
```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(caTools)
library(plotly)
library(MASS)
library(matlib)
library(dplyr)
library(pROC)
library(parallel)
library(CalibrationCurves)
source("R/Functions.R")
```

## Covariance
### Initialize variables
```{r}
# Set random seed for reproducibility
set.seed(28)
p      <- 1                               # proportion of correlated predictors
npred  <- 20                              # number of predictors
z      <- 0.2                             # z 
n      <- 100000                          # Number of samples in the dataset

# structures
mu <- c(rep(1,npred))       # vector: means
sigma <- scenario()         
```

### Experiment
```{r}
data_experiment <- mvrnorm(n, mu = mu, Sigma = sigma) %>%
  as.data.frame()

# Rename columns to "predictor1", "predictor2" ,...
colnames(data_experiment) <- c(paste0("predictor", 1:(ncol(data_experiment))))

# provide a_values
a_values <- seq(from = 0.05, to = 0.54, by = 0.005)

# For normal scenario
calculate_and_plot_auc20("AUC vs a Values for 1 end predictor: normal")

# For interaction scenario
calculate_and_plot_auc20("AUC vs a Values for 1 end predictor: interaction")

# For two normal end predictors
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 2 normal")

# For one interaction and one normal end predictor
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 1 interaction & 1 normal")

# For two interaction end predictors
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 2 interaction")
```

## No Covariance
### Initialize variables
```{r}
# Set random seed for reproducibility
set.seed(28)
z <- 0                             # z 

# structures
mu <- c(rep(1,npred))       # vector: means
sigma <- scenario()   
```

### Experiment
```{r}
data_experiment <- mvrnorm(n, mu = mu, Sigma = sigma) %>%
  as.data.frame()

# Rename columns to "predictor1", "predictor2" ,...
colnames(data_experiment) <- c(paste0("predictor", 1:(ncol(data_experiment))))

# provide a_values
a_values <- seq(from = 0.08, to = 0.9, by = 0.005)

# For normal scenario
calculate_and_plot_auc20("AUC vs a Values for 1 end predictor: normal")

# For interaction scenario
calculate_and_plot_auc20("AUC vs a Values for 1 end predictor: interaction")

# For two normal end predictors
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 2 normal")

# For one interaction and one normal end predictor
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 1 interaction & 1 normal")

# For two interaction end predictors
calculate_and_plot_auc20("AUC vs a Values for 2 end predictors: 2 interaction")
```