---
title: "Plots_docs/Thesis_Manuscript/plots/appendix"
author: "Hidde van de Beek"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
setwd(rprojroot::find_rstudio_root_file())

library(ggplot2)
library(dplyr)
library(tidyr)
library(caTools)
library(plotly)
library(MASS)
library(matlib)
library(pROC)
library(parallel)
library(CalibrationCurves)
library(caret)
library(tidyverse)
library(papaja)
library(cowplot)
library(patchwork)
library(ggh4x)
source("scripts/shared/functions.R")
```

# 5 Predictors
## normal
```{r}
### complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/percentage_5pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/auc_5pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/normal/percentage_5pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/auc_5pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

```

## interaction
```{r}
### complex
models <- c("model_interaction", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/percentage_5pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/auc_5pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/percentage_5pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/auc_5pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

```

## 2 normal
```{r}
### complex
models <- c("model_normal", "model_sparse", "model_sparse2", "model_minimal")
data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/percentage_5pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/auc_5pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normal/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normal/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/percentage_5pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/auc_5pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```

## 2 interaction
```{r}
### complex
models <- c("model_2interaction", "model_minimal", "model_interactionsparse1", "model_interactionsparse2")
data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/percentage_5pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/auc_5pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/percentage_5pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/auc_5pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```

## 2 normal + interaction
```{r}
### complex
models <- c("model_interaction", "model_interactionsparse1", "model_sparse", "model_minimal")
data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/percentage_5pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/auc_5pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/percentage_5pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/auc_5pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```

# 10 Predictors
## normal
```{r}
### complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/percentage_10pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/auc_10pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1normal/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1normal/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/normal/percentage_10pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/normal/auc_10pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

```
## interaction
```{r}
### complex
models <- c("model_interaction", "model_sparse")
data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/percentage_10pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/auc_10pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_sparse", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_sparse", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/1interaction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_sparse", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/percentage_10pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/interaction/auc_10pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

```

## 2 normal
```{r}
### complex
models <- c("model_normal", "model_sparse", "model_sparse2", "model_minimal")
data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_normal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_normal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_normal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/percentage_10pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/auc_10pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normal/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normal/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normal/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/percentage_10pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normal/auc_10pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```

## 2 interaction
```{r}
### complex
models <- c("model_2interaction", "model_minimal", "model_interactionsparse1", "model_interactionsparse2")
data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_2interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_2interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_2interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/percentage_10pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/auc_10pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2interaction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/percentage_10pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2interaction/auc_10pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```

## 2 normal + interaction
```{r}
### complex
models <- c("model_interaction", "model_interactionsparse1", "model_sparse", "model_minimal")
data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev05.rds")
p50_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)
                  
data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev05.rds")
p50_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev05.rds")
p50_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.5) 
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev02.rds")
p20_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev02.rds")
p20_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev02.rds")
p20_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.2)
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev005.rds")
p05_1 <- win_percentage(data, models, "model_interaction", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev005.rds")
p05_2 <- win_percentage(data, models, "model_interaction", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev005.rds")
p05_3 <- win_percentage(data, models, "model_interaction", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/percentage_10pred.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/auc_10pred.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)

### anti
data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev05_anti.rds")
p50_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.5)
p50_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev05_anti.rds")
p50_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.5)
p50_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev05_anti.rds")
p50_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.5)
p50_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.5)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev02_anti.rds")
p20_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.2)
p20_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev02_anti.rds")
p20_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.2)
p20_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev02_anti.rds")
p20_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.2) 
p20_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.2)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc06_ev005_anti.rds")
p05_1 <- win_percentage(data, models, "model_minimal", AUC = 0.6, EV = 0.05)
p05_auc_1 <- average_auc(data, models, AUC = 0.6, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc075_ev005_anti.rds")
p05_2 <- win_percentage(data, models, "model_minimal", AUC = 0.75, EV = 0.05)
p05_auc_2 <- average_auc(data, models, AUC = 0.75, EV = 0.05)

data <- readRDS("data/analysis/10pred/covar/2normalinteraction/auc09_ev005_anti.rds")
p05_3 <- win_percentage(data, models, "model_minimal", AUC = 0.9, EV = 0.05) 
p05_auc_3 <- average_auc(data, models, AUC = 0.9, EV = 0.05)

data_percentage <- rbind(p50_1, p50_2, p50_3, p20_1, p20_2, p20_3, p05_1, p05_2, p05_3)
data_auc <- rbind(p50_auc_1, p50_auc_2, p50_auc_3, p20_auc_1, p20_auc_2, p20_auc_3, p05_auc_1, p05_auc_2, p05_auc_3)

ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/percentage_10pred_anti.png", percentage_plot(data_percentage), width = 22.8, height = 6.5*3, dpi = 100)
ggsave("docs/Thesis_Manuscript/plots/appendix/2normalinteraction/auc_10pred_anti.png", auc_plot(data_auc), width = 22.8, height = 6.5*3, dpi = 100)
```
