---
title: "Plots_results"
author: "Hidde van de Beek"
date: "2024-05-08"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
setwd(rprojroot::find_rstudio_root_file())

library(ggplot2)
library(caTools)
library(plotly)
library(MASS)
library(matlib)
library(pROC)
library(parallel)
library(CalibrationCurves)
library(caret)
library(tidyverse)
library(papaja)
library(cowplot)
library(patchwork)
library(ggpubr)
source("scripts/shared/functions.R")
```


# Study 1
```{r}
## complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev05.rds")
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- (plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.55, max = 0.60) + theme(legend.position = "none"))

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev05.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.70, max = 0.75)  + theme(legend.position = "none", axis.title.y=element_blank())

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05.rds")
p50_3 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_3 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.85, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_1/normal.png", ggpubr::ggarrange(p50_1, p50_2, p50_3, p50_auc_1, p50_auc_2, p50_auc_3, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)

## anti
data <- readRDS("data/analysis/5pred/covar/1normal/auc06_ev05_anti.rds")
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.54, max = 0.59)  + theme(legend.position = "none")

data <- readRDS("data/analysis/5pred/covar/1normal/auc075_ev05_anti.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.69, max = 0.74) + theme(legend.position = "none", axis.title.y=element_blank())

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05_anti.rds")
p50_3 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_3 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.84, max = 0.89) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_1/anti.png", ggpubr::ggarrange(p50_1, p50_2, p50_3, p50_auc_1, p50_auc_2, p50_auc_3, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)
```

# Study 2
```{r}
## complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev005.rds")
p05 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank())
p05_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.85, max = 0.90)  + theme(legend.position = "none")

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev02.rds")
p20 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p20_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.85, max = 0.90)  + theme(legend.position = "none", axis.title.y=element_blank())

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05.rds")
p50 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.85, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_2/normal.png", ggpubr::ggarrange(p05, p20, p50, p05_auc, p20_auc, p50_auc, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)

## anti
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev005_anti.rds")
p05 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank())
p05_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.84, max = 0.89)  + theme(legend.position = "none")

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev02_anti.rds")
p20 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p20_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.84, max = 0.89) + theme(legend.position = "none", axis.title.y=element_blank())

data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05_anti.rds")
p50 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.84, max = 0.89)  + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_2/anti.png", ggpubr::ggarrange(p05, p20, p50, p05_auc, p20_auc, p50_auc, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)
```

# Study 3
```{r}
## complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05.rds")
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.87, max = 0.90)  + theme(legend.position = "none")

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev05.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.87, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_3/normal.png", ggpubr::ggarrange(p50_1, p50_2, p50_auc_1, p50_auc_2, common.legend = TRUE, legend = "right", nrow = 2, ncol = 2), width = 16.1, height = 6.5*2, dpi = 100)

## anti
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05_anti.rds")
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.86, max = 0.893)  + theme(legend.position = "none")

data <- readRDS("data/analysis/10pred/covar/1normal/auc09_ev05_anti.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.86, max = 0.893) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_3/anti.png", ggpubr::ggarrange(p50_1, p50_2, p50_auc_1, p50_auc_2, common.legend = TRUE, legend = "right", nrow = 2, ncol = 2), width = 16.1, height = 6.5*2, dpi = 100)
```

# Study 4
```{r}
## complex
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05.rds")

p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.87, max = 0.90)  + theme(legend.position = "none")

models <- c("model_interaction", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev05.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_interaction") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_interaction", min = 0.87, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_4/mixed1.png", ggpubr::ggarrange(p50_1, p50_2, p50_auc_1, p50_auc_2, common.legend = TRUE, legend = "right", nrow = 2, ncol = 2), width = 16.1, height = 6.5*2, dpi = 100)

models <- c("model_normal", "model_minimal", "model_sparse2", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev05.rds") 
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_normal") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_normal", min = 0.87, max = 0.90)  + theme(legend.position = "none")

models <- c("model_interaction", "model_minimal", "model_sparse", "model_interactionsparse1")
data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev05.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_interaction")  + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_interaction", min = 0.87, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

models <- c("model_2interaction", "model_minimal", "model_interactionsparse1", "model_interactionsparse2")
data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev05.rds")
p50_3 <- plot_win_percentage_by_sample_size(data, models, "model_2interaction") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_3 <- plot_average_auc_by_model_and_sample_size(data, models, "model_2interaction", min = 0.87, max = 0.90) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_4/mixed2.png", ggpubr::ggarrange(p50_1, p50_2, p50_3, p50_auc_1, p50_auc_2, p50_auc_3, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)

## anti
models <- c("model_normal", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1normal/auc09_ev05_anti.rds")

p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.83, max = 0.89)  + theme(legend.position = "none")

models <- c("model_interaction", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/1interaction/auc09_ev05_anti.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_sparse") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.83, max = 0.89) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_4/anti1.png", ggpubr::ggarrange(p50_1, p50_2, p50_auc_1, p50_auc_2, common.legend = TRUE, legend = "right", nrow = 2, ncol = 2), width = 16.1, height = 6.5*2, dpi = 100)

models <- c("model_normal", "model_minimal", "model_sparse2", "model_sparse")
data <- readRDS("data/analysis/5pred/covar/2normal/auc09_ev05_anti.rds") 
p50_1 <- plot_win_percentage_by_sample_size(data, models, "model_minimal") + theme(legend.position = "none", axis.title.x=element_blank())
p50_auc_1 <- plot_average_auc_by_model_and_sample_size(data, models, "model_sparse", min = 0.78, max = 0.875)  + theme(legend.position = "none")

models <- c("model_interaction", "model_minimal", "model_sparse", "model_interactionsparse1")
data <- readRDS("data/analysis/5pred/covar/2normalinteraction/auc09_ev05_anti.rds")
p50_2 <- plot_win_percentage_by_sample_size(data, models, "model_minimal")  + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_2 <- plot_average_auc_by_model_and_sample_size(data, models, "model_minimal", min = 0.78, max = 0.875) + theme(legend.position = "none", axis.title.y=element_blank())

models <- c("model_2interaction", "model_minimal", "model_interactionsparse1", "model_interactionsparse2")
data <- readRDS("data/analysis/5pred/covar/2interaction/auc09_ev05_anti.rds")
p50_3 <- plot_win_percentage_by_sample_size(data, models, "model_minimal") + theme(legend.position = "none", axis.title.x=element_blank(), axis.title.y=element_blank())
p50_auc_3 <- plot_average_auc_by_model_and_sample_size(data, models, "model_minimal", min = 0.78, max = 0.875) + theme(legend.position = "none", axis.title.y=element_blank())

ggsave("docs/Thesis_Manuscript/plots/results/study_4/anti2.png", ggpubr::ggarrange(p50_1, p50_2, p50_3, p50_auc_1, p50_auc_2, p50_auc_3, common.legend = TRUE, legend = "right"), width = 22.8, height = 6.5*2, dpi = 100)

```



